options:
    requestedVerifyOption: 'VERIFIED'

steps:
    - id: 'artifactregistry-login'
      name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'artifactregistry-login']

    - id: 'install-dependencies'
      name: 'gcr.io/cloud-builders/npm'
      args: ['ci', '--ignore-scripts']

    - id: 'build'
      name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']

artifacts:
    npmPackages:
        - repository: 'https://us-npm.pkg.dev/${PROJECT_ID}/vgen-npm-packages'
          packagePath: './'
